# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-13 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('slug', models.SlugField(max_length=255, primary_key=True, serialize=False)),
                ('english_name', models.CharField(max_length=255)),
                ('chinese_name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('english_introduction', models.TextField()),
                ('chinese_introduction', models.TextField()),
                ('english_full_description', models.TextField()),
                ('chinese_full_description', models.TextField()),
                ('event_date', models.DateField()),
                ('publish_date', models.DateField()),
            ],
            options={
                'ordering': ['-event_date', '-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255)),
                ('english_name', models.CharField(max_length=255)),
                ('chinese_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=255)),
                ('chinese_name', models.CharField(max_length=255)),
                ('english_description', models.TextField()),
                ('chinese_description', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('english_url', models.URLField()),
                ('chinese_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='MarkerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=255)),
                ('chinese_name', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('colour', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255)),
                ('english_name', models.CharField(max_length=255)),
                ('chinese_name', models.CharField(max_length=255)),
                ('english_url', models.URLField()),
                ('chinese_url', models.URLField()),
                ('logo', models.CharField(max_length=255)),
                ('english_description', models.TextField()),
                ('chinese_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('slug', models.SlugField(max_length=255, primary_key=True, serialize=False)),
                ('english_name', models.CharField(max_length=255)),
                ('chinese_name', models.CharField(max_length=255)),
                ('english_description', models.TextField()),
                ('chinese_description', models.TextField()),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSeries',
            fields=[
                ('slug', models.SlugField(max_length=255, primary_key=True, serialize=False)),
                ('english_name', models.CharField(max_length=255)),
                ('chinese_name', models.CharField(max_length=255)),
                ('english_description', models.TextField()),
                ('chinese_description', models.TextField()),
                ('icon', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ProductSeries'),
        ),
        migrations.AddField(
            model_name='partner',
            name='products',
            field=models.ManyToManyField(to='core.Product'),
        ),
        migrations.AddField(
            model_name='marker',
            name='marker_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MarkerType'),
        ),
        migrations.AddField(
            model_name='map',
            name='marker_types',
            field=models.ManyToManyField(to='core.MarkerType'),
        ),
    ]
