# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-11 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170711_0526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('introduction', models.TextField()),
                ('full_content', models.TextField()),
                ('event_date', models.DateField()),
                ('publish_date', models.DateField()),
            ],
            options={
                'ordering': ['-event_date', '-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='MapMarker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='MapType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='partners',
        ),
        migrations.AddField(
            model_name='partner',
            name='products',
            field=models.ManyToManyField(to='core.Product'),
        ),
        migrations.AddField(
            model_name='partner',
            name='story',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='mapmarker',
            name='map_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MapType'),
        ),
        migrations.AddField(
            model_name='product',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ProductSeries'),
        ),
    ]
