# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-13 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170713_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='usage_image',
            field=models.CharField(default='', max_length=255),
        ),
    ]
