# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-13 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_partner_usage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='products',
        ),
        migrations.AddField(
            model_name='partner',
            name='alliance_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partner',
            name='product_series',
            field=models.ManyToManyField(to='core.ProductSeries'),
        ),
    ]
