# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-11 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170711_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='maptype',
            name='icon',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productseries',
            name='image',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
