# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-13 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170713_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productseries',
            name='chinese_description',
        ),
        migrations.RemoveField(
            model_name='productseries',
            name='english_description',
        ),
        migrations.AddField(
            model_name='productseries',
            name='chinese_graphic',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productseries',
            name='english_graphic',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
