# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-11 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170711_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapmarker',
            name='link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
