# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-11 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mapmarker_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='maptype',
            name='colour',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
