# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-11 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_maptype_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maptype',
            name='colour',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='maptype',
            name='icon',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
