# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-11 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170711_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maptype',
            name='colour',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='maptype',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
